# -*- coding: utf-8 -*-
"""Writing_in_air.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yA21YyjPU6g4mEIyYdMew_HyDsUYls1H

## 1. Environment Check

**Before running** — if you got `RuntimeError: operator torchvision::nms does not exist`, run this once in your conda terminal:
```
conda activate sagar
pip uninstall torch torchvision torchaudio -y
pip install torch==2.1.0 torchvision==0.16.0 torchaudio==2.1.0 --index-url https://download.pytorch.org/whl/cu118
```
Then restart the kernel and continue.
"""

# Cell 1 — verify torch + torchvision are compatible
import torch
import torchvision

print(f"PyTorch    : {torch.__version__}")
print(f"torchvision: {torchvision.__version__}")
print(f"CUDA ready : {torch.cuda.is_available()}")
if torch.cuda.is_available():
    print(f"GPU        : {torch.cuda.get_device_name(0)}")
    torch.ones(1).cuda()          # smoke-test: will raise if mismatch
    print("GPU handshake OK")

# Cell 2 — install any missing pure-Python deps (safe to re-run)
import importlib.util, subprocess, sys

needed = {"editdistance": "editdistance", "skimage": "scikit-image"}
missing = [pip for mod, pip in needed.items() if importlib.util.find_spec(mod) is None]
if missing:
    subprocess.check_call([sys.executable, "-m", "pip", "install", "-q"] + missing)
    print("Installed:", missing)
else:
    print("All packages present.")

"""## 2. Import Libraries"""

import os, sys, re, time, json, copy, glob, math, random, numbers, logging, collections
import zipfile
import editdistance
import numpy as np
from PIL import Image, ImageFile
from bisect import bisect_right
import matplotlib.pyplot as plt
from matplotlib import gridspec

import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.nn.init as init
import torchvision
import torchvision.transforms as transforms
from torch.optim import Optimizer
from torch.utils.data import Dataset, DataLoader
from torch.nn.utils.rnn import pack_padded_sequence, pad_packed_sequence, pad_sequence
from torchvision.transforms import functional as TF

import PIL
import skimage
from skimage import transform as skimage_transform

ImageFile.LOAD_TRUNCATED_IMAGES = True

print(f"PyTorch version : {torch.__version__}")
print(f"CUDA available  : {torch.cuda.is_available()}")
if torch.cuda.is_available():
    print(f"GPU             : {torch.cuda.get_device_name(0)}")

"""## 3. Configuration

**`DATASET_ZIP_DIR`** — folder that contains all your `.zip` files (what you see in the VSCode explorer screenshot).  
**`DATASET_DIR`** — where extracted data will land (created automatically).  
**`CHECKPOINTS_DIR`** — where model weights are saved.
"""

class Config:
    def __init__(self):
        # ── LOCAL PATHS ────────────────────────────────────────────────────────
        # Folder containing your .zip files (matches your VSCode screenshot)
        self.zip_dir = r'I:\SAGAR\dataset'

        # Extracted dataset destination  (auto-created)
        self.dataset_dir = r'I:\SAGAR\dataset_extracted'

        # Train / val / test sub-paths (set after extraction in Cell 5)
        self.data_path_train = os.path.join(self.dataset_dir, 'english', 'train')
        self.data_path_val   = os.path.join(self.dataset_dir, 'english', 'val')
        self.data_path_test  = os.path.join(self.dataset_dir, 'english', 'test')

        # Checkpoints
        self.save_dir = r'I:\SAGAR\checkpoints'
        self.load_dir = ''

        # ── EXPERIMENT ─────────────────────────────────────────────────────────
        self.model_name = 'wita-resnet3d'

        # ── MODEL ──────────────────────────────────────────────────────────────
        self.model_type      = 'r3d'      # r2d | r3d | mc3 | rmc3 | twoplusone
        self.num_res_layer   = 1
        self.pretrained      = False
        self.recurrent_type  = 'none'     # gru | lstm | transformers | none
        self.input_size      = 256
        self.hidden_size     = 256
        self.num_layers      = 2
        self.num_encoder_layer = 6
        self.d_model         = 256
        self.nhead           = 8
        self.hidden_size_fc  = 128
        self.img_size        = 112
        self.pooling_type    = 'average'  # max | average
        self.loss_type       = 'ctc'

        # ── TRAINING ───────────────────────────────────────────────────────────
        self.track_running   = True
        self.seed_number     = 0
        self.save_frequency  = 50
        self.log_interval    = 100
        self.tensorboard_path = None

        # ── OPTIMISATION ───────────────────────────────────────────────────────
        self.batch_size       = 2         # lower if GPU OOM
        self.learning_rate    = 1e-3
        self.num_epochs       = 175
        self.optimizer_type   = 'adam'    # rmsprop | sgd | lamb | adam | adamW
        self.scheduler_type   = 'warmup'  # warmup | steplr | none
        self.scheduler_step_size = 5
        self.scheduler_gamma  = 0.9

        # ── DATASET ────────────────────────────────────────────────────────────
        self.data_type    = 'english'     # english | korean | eng_kor
        self.data_augment = False

        # ── SYSTEM ─────────────────────────────────────────────────────────────
        self.no_cuda = False
        # Windows: keep num_workers=0 to avoid DataLoader spawn issues
        self.num_workers = 0

opts = Config()
print('Configuration loaded!')
print(f'  zip_dir      : {opts.zip_dir}')
print(f'  dataset_dir  : {opts.dataset_dir}')
print(f'  save_dir     : {opts.save_dir}')

"""## 4. Extract Dataset from Zip Files

Reads all `.zip` files from `opts.zip_dir`, skips Korean-only zips, and extracts English ones into `opts.dataset_dir`.
"""

# ── Step 4a: Extract English zip files ────────────────────────────────────────
EXTRACT_DIR = os.path.join(opts.dataset_dir, 'raw')
os.makedirs(EXTRACT_DIR, exist_ok=True)

all_zips     = sorted([f for f in os.listdir(opts.zip_dir) if f.lower().endswith('.zip')])
english_zips = [f for f in all_zips if 'kor' not in f.lower()]
skipped      = [f for f in all_zips if 'kor' in f.lower()]

print(f'Total zips found : {len(all_zips)}')
print(f'Skipping {len(skipped)} Korean file(s).')
print(f'Extracting {len(english_zips)} English file(s) → {EXTRACT_DIR}\n')

for filename in english_zips:
    zip_path = os.path.join(opts.zip_dir, filename)
    # Skip if already extracted (check by presence of a marker file)
    marker = os.path.join(EXTRACT_DIR, filename + '.extracted')
    if os.path.exists(marker):
        print(f'  [skip] {filename}  (already extracted)')
        continue
    print(f'  Extracting {filename} ...')
    try:
        with zipfile.ZipFile(zip_path, 'r') as z:
            z.extractall(EXTRACT_DIR)
        open(marker, 'w').close()          # write marker
        print(f'    Done')
    except Exception as e:
        print(f'    ERROR: {e}')

print('\nExtraction complete.')

# ── Step 4b: Split extracted data → train / val / test ────────────────────────
import shutil

random.seed(42)

SPLIT = {'train': 0.8, 'val': 0.1, 'test': 0.1}
DATA_TYPE = opts.data_type   # 'english'

# Find all group dirs that have gt.txt AND at least one numeric video subdir
video_group_dirs = set()
for root, dirs, files in os.walk(EXTRACT_DIR):
    if 'gt.txt' in files:
        for d in dirs:
            subdir = os.path.join(root, d)
            if d.isdigit() and any(f.endswith('.png') for f in os.listdir(subdir)):
                video_group_dirs.add(root)
                break

video_group_dirs = sorted(video_group_dirs)
print(f'Found {len(video_group_dirs)} group folder(s) to split.')

random.shuffle(video_group_dirs)
n = len(video_group_dirs)
n_train = int(n * SPLIT['train'])
n_val   = int(n * SPLIT['val'])

splits = {
    'train': video_group_dirs[:n_train],
    'val'  : video_group_dirs[n_train: n_train + n_val],
    'test' : video_group_dirs[n_train + n_val:],
}

BASE_OUT = os.path.join(opts.dataset_dir, DATA_TYPE)
if os.path.exists(BASE_OUT):
    print(f'Removing old split at {BASE_OUT} ...')
    shutil.rmtree(BASE_OUT)
os.makedirs(BASE_OUT, exist_ok=True)

total = 0
for split_name, groups in splits.items():
    dest_split = os.path.join(BASE_OUT, split_name)
    os.makedirs(dest_split, exist_ok=True)
    count = 0
    for src in groups:
        folder_name = os.path.basename(src)
        dst = os.path.join(dest_split, folder_name)
        if not os.path.exists(dst):
            shutil.copytree(src, dst)
        count += 1
    print(f'  {split_name:5s}: {count} groups')
    total += count

print(f'\nTotal groups moved: {total}')

# Update opts paths
opts.data_path_train = os.path.join(BASE_OUT, 'train')
opts.data_path_val   = os.path.join(BASE_OUT, 'val')
opts.data_path_test  = os.path.join(BASE_OUT, 'test')
print(f'Train path: {opts.data_path_train}')
print(f'Val   path: {opts.data_path_val}')
print(f'Test  path: {opts.data_path_test}')

"""## 5. Utility Functions"""

ALPHABET  = 'abcdefghijklmnopqrstuvwxyz'
HANGUL    = 'ㄱㄴㄷㄹㅁㅂㅅㅇㅈㅊㅋㅌㅍㅎㅃㅉㄸㄲㅆㄳㄵㄶㄺㄻㄼㄽㄾㄿㅀㅀㅄㅏㅑㅓㅕㅗㅛㅜㅠㅡㅣㅐㅒㅔㅖㅘㅙㅚㅝㅞㅟㅢᴥ '
ALPHA_HAN = ALPHABET + HANGUL

def calc_seq_len_2d_kor(len_in):
    return math.floor((len_in + 2 - 2) / 2) + 1

def calc_seq_len_2d_eng(len_in):
    return math.floor((len_in - 2) / 2) + 1

def calc_seq_len(len_in):
    """r3d / twoplusone (English)"""
    o = math.floor((len_in - 3 + 2) / 2) + 1
    return math.floor((o - 3 + 2) / 2) + 1

def calc_seq_len_mc3(len_in):
    o = math.floor((len_in - 3 + 2) / 2) + 1
    return math.floor((o - 2) / 2) + 1

def calc_seq_len_rmc3(len_in):
    o = math.floor((len_in - 2) / 2) + 1
    return math.floor((o - 3 + 2) / 2) + 1

def seq_len_r3d_kor(len_in):
    o = len_in + 2
    o = math.floor((o - 3 + 2) / 2) + 1
    return math.floor((o - 3 + 2) / 2) + 1

def seq_len_mc3_kor(len_in):
    o = len_in + 2
    o = math.floor((o - 3 + 2) / 2) + 1
    return math.floor((o - 2) / 2) + 1

def seq_len_rmc3_kor(len_in):
    o = len_in + 2
    o = math.floor((o - 2) / 2) + 1
    return math.floor((o - 3 + 2) / 2) + 1

def sec_to_hm(t):
    t = int(t); s = t % 60; t //= 60; m = t % 60; t //= 60
    return t, m, s

def sec_to_hm_str(t):
    h, m, s = sec_to_hm(t)
    return f"{h:02d}h{m:02d}m{s:02d}s"

class StrLabelConverter:
    """Encode/decode strings to/from integer label tensors for CTC."""

    def __init__(self, alphabet, ignore_case=True):
        self._ignore_case = ignore_case
        if ignore_case:
            alphabet = alphabet.lower()
        self.alphabet = alphabet + '-'
        self.dict = {c: i + 1 for i, c in enumerate(self.alphabet)}

    def encode(self, text):
        if isinstance(text, str):
            lst, prev = [], ''
            for ch in text:
                if ch == prev:
                    lst.append(self.dict['-'])
                lst.append(self.dict[ch.lower() if self._ignore_case else ch])
                prev = ch
            return torch.IntTensor(lst), torch.IntTensor([len(lst)])
        elif isinstance(text, collections.abc.Iterable):
            lengths = [len(s) for s in text]
            joined, _ = self.encode(''.join(text))
            return joined, torch.IntTensor(lengths)

    def decode(self, t, length, raw=False):
        if length.numel() == 1:
            length = length[0]
            assert t.numel() == length
            if raw:
                return ''.join(self.alphabet[i - 1] for i in t)
            chars = []
            for i in range(int(length)):
                if t[i] != 0 and not (i > 0 and t[i - 1] == t[i]):
                    chars.append(self.alphabet[t[i] - 1])
            return ''.join(chars)
        texts, idx = [], 0
        for l in length:
            texts.append(self.decode(t[idx: idx + l], torch.IntTensor([l]), raw))
            idx += l
        return texts


def cer(ref, hyp):
    ref = re.sub(r'^<START>|<EOS>$', '', ref)
    hyp = re.sub(r'^<START>|<EOS>$', '', hyp)
    return editdistance.eval(ref, hyp), len(ref)

def wer(ref, hyp):
    ref = re.sub(r'^<START>|<EOS>$', '', ref)
    hyp = re.sub(r'^<START>|<EOS>$', '', hyp)
    return editdistance.eval(ref.split(), hyp.split()), len(ref.split())

"""## 6. Scheduler & Optimizer"""

class WarmupMultiStepLR(torch.optim.lr_scheduler._LRScheduler):
    def __init__(self, optimizer, milestones, gamma=0.1,
                 warmup_factor=1/3, warmup_iters=500,
                 warmup_method='linear', last_epoch=-1):
        assert list(milestones) == sorted(milestones), 'Milestones must be sorted'
        assert warmup_method in ('constant', 'linear')
        self.milestones = milestones
        self.gamma = gamma
        self.warmup_factor = warmup_factor
        self.warmup_iters = warmup_iters
        self.warmup_method = warmup_method
        super().__init__(optimizer, last_epoch)

    def get_lr(self):
        wf = 1
        if self.last_epoch < self.warmup_iters:
            if self.warmup_method == 'constant':
                wf = self.warmup_factor
            else:
                alpha = self.last_epoch / self.warmup_iters
                wf = self.warmup_factor * (1 - alpha) + alpha
        return [lr * wf * self.gamma ** bisect_right(self.milestones, self.last_epoch)
                for lr in self.base_lrs]


class Lamb(Optimizer):
    """LAMB optimizer — large-batch training."""
    def __init__(self, params, lr=1e-3, betas=(0.9, 0.999), eps=1e-6,
                 weight_decay=0, adam=False):
        defaults = dict(lr=lr, betas=betas, eps=eps, weight_decay=weight_decay)
        self.adam = adam
        super().__init__(params, defaults)

    def step(self, closure=None):
        loss = closure() if closure else None
        for group in self.param_groups:
            for p in group['params']:
                if p.grad is None: continue
                grad = p.grad.data
                state = self.state[p]
                if not state:
                    state['step'] = 0
                    state['exp_avg']    = torch.zeros_like(p.data)
                    state['exp_avg_sq'] = torch.zeros_like(p.data)
                ea, eas = state['exp_avg'], state['exp_avg_sq']
                b1, b2  = group['betas']
                state['step'] += 1
                ea.mul_(b1).add_(grad, alpha=1 - b1)
                eas.mul_(b2).addcmul_(grad, grad, value=1 - b2)
                adam_step = ea / eas.sqrt().add(group['eps'])
                if group['weight_decay']:
                    adam_step.add_(p.data, alpha=group['weight_decay'])
                wn = p.data.pow(2).sum().sqrt().clamp(0, 10)
                an = adam_step.pow(2).sum().sqrt()
                tr = 1 if (wn == 0 or an == 0 or self.adam) else wn / an
                p.data.add_(adam_step, alpha=-group['lr'] * tr)
        return loss

"""## 7. Video Transforms"""

def convert_img(img):
    if len(img.shape) == 3: return img.transpose(2, 0, 1)
    if len(img.shape) == 2: return np.expand_dims(img, 0)
    return img


def _is_tensor_clip(clip):
    return torch.is_tensor(clip) and clip.ndimension() == 4


def normalize_clip(clip, mean, std, inplace=False):
    if not inplace: clip = clip.clone()
    dtype = clip.dtype
    mean = torch.as_tensor(mean, dtype=dtype, device=clip.device)
    std  = torch.as_tensor(std,  dtype=dtype, device=clip.device)
    clip.sub_(mean[:, None, None, None]).div_(std[:, None, None, None])
    return clip


class ClipToTensor:
    def __init__(self, channel_nb=3, div_255=True, numpy=False):
        self.channel_nb = channel_nb
        self.div_255 = div_255
        self.numpy = numpy

    def __call__(self, clip):
        if isinstance(clip[0], np.ndarray):
            h, w, ch = clip[0].shape
        elif isinstance(clip[0], Image.Image):
            w, h = clip[0].size
        else:
            raise TypeError(type(clip[0]))
        np_clip = np.zeros([self.channel_nb, len(clip), int(h), int(w)])
        for i, img in enumerate(clip):
            if isinstance(img, Image.Image): img = np.array(img, copy=False)
            np_clip[:, i] = convert_img(img)
        if self.numpy:
            return np_clip / 255 if self.div_255 else np_clip
        t = torch.from_numpy(np_clip).float()
        return t.div(255) if self.div_255 else t


class VideoNormalize:
    def __init__(self, mean, std):
        self.mean, self.std = mean, std
    def __call__(self, clip):
        return normalize_clip(clip, self.mean, self.std)


class VideoCompose:
    def __init__(self, transforms):
        self.transforms = transforms
    def __call__(self, clip):
        for t in self.transforms: clip = t(clip)
        return clip


class ColorJitter:
    def __init__(self, brightness=0, contrast=0, saturation=0, hue=0):
        self.brightness = brightness
        self.contrast   = contrast
        self.saturation = saturation
        self.hue        = hue

    def get_params(self, b, c, s, h):
        def rf(x): return random.uniform(max(0, 1-x), 1+x) if x else None
        return rf(b), rf(c), rf(s), random.uniform(-h, h) if h else None

    def __call__(self, clip):
        b, c, s, h = self.get_params(self.brightness, self.contrast, self.saturation, self.hue)
        fns = []
        if b is not None: fns.append(lambda img, _b=b: TF.adjust_brightness(img, _b))
        if s is not None: fns.append(lambda img, _s=s: TF.adjust_saturation(img, _s))
        if h is not None: fns.append(lambda img, _h=h: TF.adjust_hue(img, _h))
        if c is not None: fns.append(lambda img, _c=c: TF.adjust_contrast(img, _c))
        random.shuffle(fns)
        out = []
        for img in clip:
            for fn in fns: img = fn(img)
            out.append(img)
        return out


class RandomRotation:
    def __init__(self, degrees):
        if isinstance(degrees, numbers.Number):
            self.degrees = (-abs(degrees), abs(degrees))
        else:
            self.degrees = degrees

    def __call__(self, clip):
        angle = random.uniform(*self.degrees)
        if isinstance(clip[0], np.ndarray):
            return [skimage_transform.rotate(f, angle) for f in clip]
        elif isinstance(clip[0], Image.Image):
            return [f.rotate(angle) for f in clip]
        raise TypeError(type(clip[0]))

"""## 8. ResNet3D Model"""

TRACK_RUNNING       = opts.track_running
NUM_LAYER           = opts.num_res_layer
STEM_TEMPORAL_KERNEL = 1 if opts.data_type == 'korean' and NUM_LAYER == 2 else 3


class Conv3DSimple(nn.Conv3d):
    def __init__(self, in_planes, out_planes, midplanes=None, stride=1, padding=1):
        super().__init__(in_planes, out_planes, (3,3,3), stride, padding, bias=False)
    @staticmethod
    def get_downsample_stride(s): return (s,s,s)


class Conv2Plus1D(nn.Sequential):
    def __init__(self, in_planes, out_planes, midplanes, stride=1, padding=1):
        super().__init__(
            nn.Conv3d(in_planes, midplanes, (1,3,3), (1,stride,stride), (0,padding,padding), bias=False),
            nn.BatchNorm3d(midplanes, track_running_stats=TRACK_RUNNING),
            nn.ReLU(inplace=True),
            nn.Conv3d(midplanes, out_planes, (3,1,1), (stride,1,1), (padding,0,0), bias=False))
    @staticmethod
    def get_downsample_stride(s): return (s,s,s)


class Conv3DNoTemporal(nn.Conv3d):
    def __init__(self, in_planes, out_planes, midplanes=None, stride=1, padding=1):
        super().__init__(in_planes, out_planes, (1,3,3), (1,stride,stride), (0,padding,padding), bias=False)
    @staticmethod
    def get_downsample_stride(s): return (1,s,s)


class BasicBlock(nn.Module):
    expansion = 1
    def __init__(self, inplanes, planes, conv_builder, stride=1, downsample=None):
        midplanes = (inplanes * planes * 27) // (inplanes * 9 + 3 * planes)
        super().__init__()
        self.conv1 = nn.Sequential(
            conv_builder(inplanes, planes, midplanes, stride),
            nn.BatchNorm3d(planes, track_running_stats=TRACK_RUNNING), nn.ReLU(inplace=True))
        self.conv2 = nn.Sequential(
            conv_builder(planes, planes, midplanes),
            nn.BatchNorm3d(planes, track_running_stats=TRACK_RUNNING))
        self.relu = nn.ReLU(inplace=True)
        self.downsample = downsample

    def forward(self, x):
        residual = x
        out = self.conv2(self.conv1(x))
        if self.downsample: residual = self.downsample(x)
        return self.relu(out + residual)


class BasicStem(nn.Sequential):
    def __init__(self):
        super().__init__(
            nn.Conv3d(3, 64, (STEM_TEMPORAL_KERNEL,7,7), (1,2,2), (1,3,3), bias=False),
            nn.BatchNorm3d(64, track_running_stats=TRACK_RUNNING), nn.ReLU(inplace=True))


class R2Plus1dStem(nn.Sequential):
    def __init__(self):
        super().__init__(
            nn.Conv3d(3, 45, (1,7,7), (1,2,2), (0,3,3), bias=False),
            nn.BatchNorm3d(45, track_running_stats=TRACK_RUNNING), nn.ReLU(inplace=True),
            nn.Conv3d(45, 64, (3,1,1), (1,1,1), (1,0,0), bias=False),
            nn.BatchNorm3d(64, track_running_stats=TRACK_RUNNING), nn.ReLU(inplace=True))


class VideoResNet(nn.Module):
    def __init__(self, block, conv_makers, layers, stem, num_classes=256):
        super().__init__()
        self.inplanes = 64
        self.stem   = stem()
        self.layer1 = self._make_layer(block, conv_makers[0],  64, layers[0], stride=1)
        self.layer2 = self._make_layer(block, conv_makers[1], 128, layers[1], stride=2)
        self.layer3 = self._make_layer(block, conv_makers[2], 256, layers[2], stride=1)
        self.layer4 = self._make_layer(block, conv_makers[3], 512, layers[3], stride=2)
        self.maxpool          = nn.MaxPool3d((2,3,3))
        self.avgpool          = nn.AvgPool3d((2,3,3))
        self.adaptive_avgpool = nn.AdaptiveAvgPool3d((None,1,1))
        self.adaptive_maxpool = nn.AdaptiveMaxPool3d((None,1,1))
        self.fc = nn.Linear(512 * block.expansion, num_classes)
        self._init_weights()

    def forward(self, x):
        x = self.stem(x)
        x = self.layer1(x)
        x = self.layer2(x)
        if opts.model_type not in ('r3d', 'twoplusone'):
            x = self.maxpool(x) if opts.pooling_type == 'max' else self.avgpool(x)
        x = self.layer3(x)
        x = self.layer4(x)
        x = self.adaptive_avgpool(x) if opts.pooling_type == 'average' else self.adaptive_maxpool(x)
        dev_count = torch.cuda.device_count() if torch.cuda.is_available() else 1
        if opts.batch_size / dev_count <= 1:
            x = x.squeeze().unsqueeze(0).unsqueeze(2).permute(0,2,1) if x.shape[2]==1 \
                else x.squeeze().unsqueeze(0).permute(0,2,1)
        else:
            x = x.squeeze().permute(0,2,1)
        return self.fc(x)

    def _make_layer(self, block, conv_builder, planes, n_blocks, stride=1):
        ds = None
        if stride != 1 or self.inplanes != planes:
            ds_stride = conv_builder.get_downsample_stride(stride)
            ds = nn.Sequential(
                nn.Conv3d(self.inplanes, planes, 1, ds_stride, bias=False),
                nn.BatchNorm3d(planes, track_running_stats=TRACK_RUNNING))
        layers = [block(self.inplanes, planes, conv_builder, stride, ds)]
        self.inplanes = planes
        for _ in range(1, n_blocks):
            layers.append(block(planes, planes, conv_builder))
        return nn.Sequential(*layers)

    def _init_weights(self):
        for m in self.modules():
            if isinstance(m, nn.Conv3d):
                nn.init.kaiming_normal_(m.weight, mode='fan_out', nonlinearity='relu')
                if m.bias is not None: nn.init.constant_(m.bias, 0)
            elif isinstance(m, nn.BatchNorm3d):
                nn.init.constant_(m.weight, 1); nn.init.constant_(m.bias, 0)
            elif isinstance(m, nn.Linear):
                nn.init.normal_(m.weight, 0, 0.01); nn.init.constant_(m.bias, 0)


L = [NUM_LAYER] * 4
def r2d(**kw):      return VideoResNet(BasicBlock, [Conv3DNoTemporal]*4, L, BasicStem, **kw)
def r3d(**kw):      return VideoResNet(BasicBlock, [Conv3DSimple]*4,     L, BasicStem, **kw)
def mc3(**kw):      return VideoResNet(BasicBlock, [Conv3DSimple]*2 + [Conv3DNoTemporal]*2, L, BasicStem, **kw)
def rmc3(**kw):     return VideoResNet(BasicBlock, [Conv3DNoTemporal]*2 + [Conv3DSimple]*2, L, BasicStem, **kw)
def r2plus1d(**kw): return VideoResNet(BasicBlock, [Conv2Plus1D]*4,      L, R2Plus1dStem, **kw)

print('Model definitions loaded.')

"""## 9. GestureTranslator Model"""

class GestureTranslator(nn.Module):
    def __init__(self, opts):
        super().__init__()
        self.opts = opts

        alpha_map = {'english': ALPHABET, 'korean': HANGUL}
        alpha = alpha_map.get(opts.data_type, ALPHA_HAN)
        # FIX: CTC only needs +1 for blank token (index 0), chars use indices 1-27
        self.num_class = len(alpha) + 1  # Was: len(alpha) + (2 if opts.loss_type == 'ctc' else 1)

        builders = {'r3d': r3d, 'mc3': mc3, 'rmc3': rmc3, 'twoplusone': r2plus1d, 'r2d': r2d}
        self.encoder_module = builders[opts.model_type]()

        if opts.pretrained:
            # Use weights=None / weights=... API (no deprecation warning)
            pt_map = {
                'r3d':      torchvision.models.video.R3D_18_Weights.DEFAULT,
                'mc3':      torchvision.models.video.MC3_18_Weights.DEFAULT,
                'twoplusone': torchvision.models.video.R2Plus1D_18_Weights.DEFAULT,
            }
            if opts.model_type in pt_map:
                try:
                    model_ft = getattr(torchvision.models.video,
                                       {'r3d':'r3d_18','mc3':'mc3_18','twoplusone':'r2plus1d_18'}[opts.model_type])(
                                       weights=pt_map[opts.model_type])
                except Exception:
                    model_ft = getattr(torchvision.models.video,
                                       {'r3d':'r3d_18','mc3':'mc3_18','twoplusone':'r2plus1d_18'}[opts.model_type])(
                                       pretrained=True)
                pre = model_ft.state_dict()
                pre.pop('fc.weight', None); pre.pop('fc.bias', None)
                enc = self.encoder_module.state_dict()
                enc.update(pre)
                self.encoder_module.load_state_dict(enc)

        self.recurrent_module = None
        rt = opts.recurrent_type.lower()
        if rt == 'lstm':
            self.recurrent_module = nn.LSTM(opts.input_size, opts.hidden_size,
                                            opts.num_layers, batch_first=True, bidirectional=True)
        elif rt == 'gru':
            self.recurrent_module = nn.GRU(opts.input_size, opts.hidden_size,
                                           opts.num_layers, batch_first=True, bidirectional=True)
        elif rt == 'transformers':
            enc_layer = nn.TransformerEncoderLayer(d_model=opts.d_model, nhead=opts.nhead, batch_first=True)
            self.recurrent_module = nn.TransformerEncoder(enc_layer, opts.num_encoder_layer)

        if self.recurrent_module and rt != 'transformers':
            self.fc1 = nn.Linear(2 * opts.hidden_size, opts.hidden_size_fc)
        elif self.recurrent_module and rt == 'transformers':
            self.fc1 = nn.Linear(opts.d_model, opts.hidden_size_fc)
        else:
            self.fc1 = None

        in_fc2 = opts.hidden_size_fc if self.fc1 else opts.input_size
        self.fc2 = nn.Linear(in_fc2, self.num_class)

    def forward(self, seq_img, seq_lens):
        emb = self.encoder_module(seq_img.permute(0,2,1,3,4))
        rt = self.opts.recurrent_type.lower()
        if self.recurrent_module and rt != 'transformers':
            packed, _ = self.recurrent_module(
                pack_padded_sequence(emb, seq_lens.cpu(), batch_first=True, enforce_sorted=False))
            emb, _ = pad_packed_sequence(packed, batch_first=True)
            return self.fc2(F.relu(self.fc1(emb)))
        elif self.recurrent_module:
            return self.fc2(F.relu(self.fc1(self.recurrent_module(emb))))
        return self.fc2(emb)

print('GestureTranslator defined.')

"""## 10. Dataset"""

class hgtk:                    # dummy for English-only mode
    class text:
        @staticmethod
        def decompose(t): return t


class AirTypingDataset(Dataset):
    def __init__(self, opts, data_path):
        self.data_path    = data_path
        self.data_type    = opts.data_type
        self.data_augment = opts.data_augment

        alpha_map = {'english': (ALPHABET, True), 'korean': (HANGUL, False)}
        alpha, ic = alpha_map.get(opts.data_type, (ALPHA_HAN, False))
        self.converter = StrLabelConverter(alpha, ic)

        self.video_list = []
        for group_dir in sorted(glob.glob(os.path.join(data_path, '*'))):
            if not os.path.isdir(group_dir): continue
            if not os.path.exists(os.path.join(group_dir, 'gt.txt')): continue
            for item in os.listdir(group_dir):
                vdir = os.path.join(group_dir, item)
                if os.path.isdir(vdir) and item.isdigit():
                    if any(f.endswith('.png') for f in os.listdir(vdir)):
                        self.video_list.append(vdir)

        self.img_size = opts.img_size
        self.resize = transforms.Resize(112)

        self.video_transform = VideoCompose([
            ClipToTensor(channel_nb=3),
            VideoNormalize(mean=[0.485,0.456,0.406], std=[0.229,0.224,0.225])
        ])
        self.video_transform_aug = VideoCompose([
            ColorJitter(0.5,0.5,0.5,0.5),
            RandomRotation(5),
            ClipToTensor(channel_nb=3),
            VideoNormalize(mean=[0.485,0.456,0.406], std=[0.229,0.224,0.225])
        ])

        self.labels = []
        for vname in self.video_list:
            idx = int(os.path.basename(vname))
            gt_path = os.path.join(os.path.dirname(vname), 'gt.txt')
            if self.data_type == 'english':
                with open(gt_path, 'r') as f:
                    self.labels.append(f.readlines()[idx].strip())
            elif self.data_type == 'korean':
                with open(gt_path, 'rb') as f:
                    self.labels.append(f.readlines()[idx][:-2].decode('cp949'))

        print(f'Dataset loaded from {data_path}: {len(self.video_list)} samples')

    def __len__(self):  return len(self.video_list)

    def __getitem__(self, i):
        return self.read_images(i).permute(1,0,2,3), self.read_labels(i)

    def read_images(self, i):
        vdir = self.video_list[i]
        if os.path.isfile(vdir): vdir = os.path.dirname(vdir)
        frames = sorted(f for f in os.listdir(vdir) if f.endswith('.png'))
        imgs = []
        for fn in frames:
            img = Image.open(os.path.join(vdir, fn))
            if self.img_size == 112: img = self.resize(img)
            imgs.append(img)
        return self.video_transform_aug(imgs) if self.data_augment else self.video_transform(imgs)

    def read_labels(self, i):
        raw = hgtk.text.decompose(self.labels[i]) if self.data_type == 'korean' else self.labels[i]
        enc, _ = self.converter.encode(raw)
        return enc

"""## 11. Collate & Trainer"""

def pad_collate(batch):
    xx, yy = zip(*batch)
    yy_pad = pad_sequence(yy, batch_first=True, padding_value=0)
    xx_pad = pad_sequence(xx, batch_first=True, padding_value=0)

    eng = opts.data_type == 'english'
    kor1 = opts.data_type == 'korean' and opts.num_res_layer == 1
    kor2 = opts.data_type == 'korean' and opts.num_res_layer == 2

    if eng or kor1:
        fn_map = {'r3d': calc_seq_len, 'twoplusone': calc_seq_len,
                  'rmc3': calc_seq_len_rmc3, 'mc3': calc_seq_len_mc3, 'r2d': calc_seq_len_2d_eng}
        fn = fn_map.get(opts.model_type, calc_seq_len)
    elif kor2:
        fn_map = {'r3d': seq_len_r3d_kor, 'twoplusone': calc_seq_len,
                  'rmc3': seq_len_rmc3_kor, 'mc3': seq_len_mc3_kor, 'r2d': calc_seq_len_2d_kor}
        fn = fn_map.get(opts.model_type, seq_len_r3d_kor)

    x_lens = torch.LongTensor([fn(len(x)) for x in xx])
    y_lens = torch.LongTensor([len(y) for y in yy])
    return xx_pad, yy_pad, x_lens, y_lens

class Trainer:
    def __init__(self, opts):
        self.opts = opts
        self.save_dir = os.path.join(opts.save_dir, opts.model_name)
        os.makedirs(self.save_dir, exist_ok=True)

        logging.basicConfig(
            filename=os.path.join(self.save_dir, 'log-train.log'),
            format='%(asctime)s %(message)s', datefmt='%m/%d/%Y %p %I:%M:%S',
            level=logging.INFO)
        self.logger = logging.getLogger('trainLogger')
        if not self.logger.handlers:
            self.logger.addHandler(logging.StreamHandler(sys.stdout))

        self.device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

        # Datasets
        data_train = AirTypingDataset(opts, opts.data_path_train)
        data_val   = AirTypingDataset(opts, opts.data_path_val)
        data_test  = AirTypingDataset(opts, opts.data_path_test)

        dl_kw = dict(batch_size=opts.batch_size, collate_fn=pad_collate,
                     num_workers=opts.num_workers, drop_last=True)
        self.data_loader_train = DataLoader(data_train, shuffle=True,  **dl_kw)
        self.data_loader_val   = DataLoader(data_val,   shuffle=False, **dl_kw)
        self.data_loader_test  = DataLoader(data_test,  shuffle=False, **dl_kw)

        self.model = GestureTranslator(opts).to(self.device)
        self.model_without_dp = self.model
        if torch.cuda.device_count() > 1:
            self.model = nn.DataParallel(self.model)
            self.model_without_dp = self.model.module
        self.logger.info(f'Device: {self.device}')

        params = list(self.model_without_dp.parameters())
        opt_map = {
            'adam':    torch.optim.Adam,
            'adamW':   torch.optim.AdamW,
            'sgd':     torch.optim.SGD,
            'rmsprop': torch.optim.RMSprop,
            'lamb':    Lamb,
        }
        self.optimizer = opt_map[opts.optimizer_type](params, lr=opts.learning_rate)

        iter_size = len(self.data_loader_train)
        step = opts.scheduler_step_size * iter_size
        if opts.scheduler_type == 'warmup':
            self.scheduler = WarmupMultiStepLR(
                self.optimizer, [step*(i+1) for i in range(opts.num_epochs)],
                gamma=opts.scheduler_gamma, warmup_iters=500)
        elif opts.scheduler_type == 'steplr':
            self.scheduler = torch.optim.lr_scheduler.StepLR(
                self.optimizer, step_size=step, gamma=opts.scheduler_gamma)
        else:
            self.scheduler = None

        if opts.load_dir:
            self.load_model()

        self.ctc_loss = nn.CTCLoss(reduction='mean', zero_infinity=True)
        self.epoch = self.step = self.start_step = 0
        self.start_time = time.time()
        self.num_total_steps = iter_size * opts.num_epochs
        self.best_val_cer = float('inf')
        self.save_opts()

    # ── Training loop ──────────────────────────────────────────────────────
    def train(self):
        for self.epoch in range(self.opts.num_epochs):
            print(f'Epoch {self.epoch}')
            self.model.train()
            self.run_one_epoch()
            is_best = self.validate(self.data_loader_val)
            if is_best or (self.opts.save_frequency > 0 and
                           (self.epoch+1) % self.opts.save_frequency == 0):
                self.save_model(is_best)

    def run_one_epoch(self):
        losses = []
        for bi, (xp, yp, xl, yl) in enumerate(self.data_loader_train):
            t0 = time.time()
            xp, yp = xp.to(self.device), yp.to(self.device)
            xl, yl = xl.to(self.device), yl.to(self.device)
            self.optimizer.zero_grad()
            out = self.model(xp, xl).permute(1,0,2).log_softmax(2)
            loss = self.ctc_loss(out, yp, xl, yl)
            losses.append(loss.item())
            loss.backward()
            self.optimizer.step()
            if self.scheduler: self.scheduler.step()
            if (bi+1) % self.opts.log_interval == 0:
                self.log_time(time.time()-t0, bi, loss.item())
                y_pred = torch.max(out, 2)[1]
                self.logger.info('\tGT  : ' + self.data_loader_train.dataset.converter.decode(yp[0,:yl[0]], yl[:1]))
                self.logger.info('\tPred: ' + self.data_loader_train.dataset.converter.decode(y_pred[:xl[0],0], xl[:1]))
            self.step += 1
        return losses

    def validate(self, data_loader, load=False):
        self.logger.info('--- Validation ---')
        if load: self.load_model()
        self.model.eval()
        losses, total_err, total_len = [], 0, 0
        with torch.no_grad():
            for bi, (xp, yp, xl, yl) in enumerate(data_loader):
                xp, yp = xp.to(self.device), yp.to(self.device)
                xl, yl = xl.to(self.device), yl.to(self.device)
                out = self.model(xp, xl).permute(1,0,2).log_softmax(2)
                losses.append(self.ctc_loss(out, yp, xl, yl).item())
                y_pred = torch.max(out, 2)[1]
                gt   = data_loader.dataset.converter.decode(yp[0,:yl[0]], yl[:1])
                pred = data_loader.dataset.converter.decode(y_pred[:xl[0],0], xl[:1])
                err, length = cer(gt, pred)
                total_err += min(err, length); total_len += length
                if (bi+1) % self.opts.log_interval == 0:
                    self.logger.info(f'\tGT  : {gt}'); self.logger.info(f'\tPred: {pred}')
        cur_cer = total_err / max(total_len, 1)
        self.logger.info(f'\tval_loss={sum(losses)/len(losses):.4f}  val_cer={cur_cer:.4f}')
        if cur_cer < self.best_val_cer:
            self.best_val_cer = cur_cer
            return True
        return False

    def log_time(self, duration, bi, loss):
        sps = self.opts.batch_size / max(duration, 1e-6)
        elapsed = time.time() - self.start_time
        left = ((self.num_total_steps - self.step) / max(self.step - self.start_step, 1)) * elapsed
        self.logger.info(
            f'epoch {self.epoch:3d} | batch [{bi*self.opts.batch_size:4d}/{len(self.data_loader_train.dataset)}]'
            f' | ex/s:{sps:5.1f} | loss:{loss:.5f} | elapsed:{sec_to_hm_str(elapsed)} | left:{sec_to_hm_str(left)}')

    def save_opts(self):
        with open(os.path.join(self.save_dir, 'opts.json'), 'w') as f:
            json.dump(self.opts.__dict__, f, indent=2)

    def save_model(self, is_best):
        tag = f'weights_{self.epoch}{"_best" if is_best else ""}'
        folder = os.path.join(self.save_dir, 'models', tag)
        os.makedirs(folder, exist_ok=True)
        torch.save(self.model_without_dp.state_dict(), os.path.join(folder, 'model.pth'))
        torch.save(self.optimizer.state_dict(),         os.path.join(folder, 'optimizer.pth'))
        if self.scheduler:
            torch.save(self.scheduler.state_dict(), os.path.join(folder, 'scheduler.pth'))
        print(f'Saved checkpoint → {folder}')

    def load_model(self):
        d = os.path.expanduser(self.opts.load_dir)
        assert os.path.isdir(d), f'Cannot find {d}'
        print(f'Loading model from {d}')
        self.model_without_dp.load_state_dict(torch.load(os.path.join(d, 'model.pth'), map_location=self.device))
        for name, cls in [('optimizer', self.optimizer), ('scheduler', self.scheduler)]:
            p = os.path.join(d, f'{name}.pth')
            if cls and os.path.isfile(p):
                cls.load_state_dict(torch.load(p, map_location=self.device))

print('Trainer defined.')

"""## 12. Configure Training Run"""

# Tweak any opts here before training
opts.model_name   = 'r3d_local_eng'
opts.model_type   = 'r3d'
opts.pooling_type = 'average'
opts.data_type    = 'english'
opts.batch_size   = 1          # lower to 1 if you get CUDA out-of-memory
opts.num_epochs   = 50         # increase to 175 for full training
opts.log_interval = 10
opts.num_workers  = 0          # keep 0 on Windows
opts.data_augment = True

# Reproducibility
random.seed(opts.seed_number)
np.random.seed(opts.seed_number)
torch.manual_seed(opts.seed_number)
if torch.cuda.is_available():
    torch.cuda.manual_seed(opts.seed_number)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark     = False

print('Run config:')
for k, v in opts.__dict__.items():
    print(f'  {k}: {v}')

"""## 13. Train"""

trainer = Trainer(opts)
trainer.train()

"""## 14. Evaluate on Test Set"""

trainer.validate(trainer.data_loader_test, load=False)

# Load a saved checkpoint and evaluate
def load_and_evaluate(model_path):
    opts.load_dir = model_path
    t = Trainer(opts)
    t.validate(t.data_loader_test, load=True)

# Example:
# load_and_evaluate(r'C:\Users\SHIVAM\SAGAR\checkpoints\r3d_local_eng\models\weights_0_best')

"""## 15. Visualise a Dataset Sample"""

def visualize_sample(dataset, index=0):
    video_tensor, video_label = dataset[index]
    label_text = dataset.converter.decode(video_label, torch.IntTensor([len(video_label)]))
    n = video_tensor.shape[0]
    cols = 5; rows = min(5, (n + cols - 1) // cols)
    fig, axes = plt.subplots(rows, cols, figsize=(15, 3*rows))
    fig.suptitle(f'Label: {label_text}', fontsize=16)
    axes = axes.flatten() if rows > 1 else list(axes)
    mean = np.array([0.485,0.456,0.406]); std = np.array([0.229,0.224,0.225])
    for i in range(rows * cols):
        if i < n:
            frame = np.clip(std * video_tensor[i].permute(1,2,0).numpy() + mean, 0, 1)
            axes[i].imshow(frame); axes[i].set_title(f'Frame {i}')
        axes[i].axis('off')
    plt.tight_layout(); plt.show()

# Usage after datasets are ready:
from torch.utils.data import DataLoader
ds = AirTypingDataset(opts, opts.data_path_train)
visualize_sample(ds, 0)

"""## 16. Inference on a Single Video Folder"""

def inference_single_video(model, video_path, opts):
    """Run inference on one folder of PNG frames."""
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    model.eval()
    vt = VideoCompose([
        ClipToTensor(channel_nb=3),
        VideoNormalize(mean=[0.485,0.456,0.406], std=[0.229,0.224,0.225])
    ])
    resize = transforms.Resize(112)
    frames = sorted(f for f in os.listdir(video_path) if f.endswith('.png'))
    imgs = []
    for fn in frames:
        img = Image.open(os.path.join(video_path, fn))
        if opts.img_size == 112: img = resize(img)
        imgs.append(img)
    vid = vt(imgs).permute(1,0,2,3).unsqueeze(0).to(device)
    fn_map = {'r3d': calc_seq_len, 'twoplusone': calc_seq_len,
              'mc3': calc_seq_len_mc3, 'rmc3': calc_seq_len_rmc3,
              'r2d': calc_seq_len_2d_eng}
    seq_len = fn_map.get(opts.model_type, calc_seq_len)(len(frames))
    xl = torch.LongTensor([seq_len]).to(device)
    with torch.no_grad():
        out = model(vid, xl).permute(1,0,2).log_softmax(2)
        y_pred = torch.max(out, 2)[1]
    return StrLabelConverter(ALPHABET).decode(y_pred[:xl[0], 0], xl[:1])

# Example:
# result = inference_single_video(trainer.model, r'C:\path\to\frame_folder', opts)
# print('Predicted:', result)

# Visualization graphs: split distribution + label length + frame count statistics

# Reuse existing training dataset if available
dataset_vis = ds if 'ds' in globals() else AirTypingDataset(opts, opts.data_path_train)

def _count_samples(split_path):
    c = 0
    for group_dir in glob.glob(os.path.join(split_path, '*')):
        if not os.path.isdir(group_dir):
            continue
        for item in os.listdir(group_dir):
            vdir = os.path.join(group_dir, item)
            if os.path.isdir(vdir) and item.isdigit():
                if any(f.endswith('.png') for f in os.listdir(vdir)):
                    c += 1
    return c

split_names = ['train', 'val', 'test']
split_paths = [opts.data_path_train, opts.data_path_val, opts.data_path_test]
split_counts = [_count_samples(p) for p in split_paths]

label_lengths = [len(x) for x in dataset_vis.labels]
frame_counts = []
for vdir in dataset_vis.video_list:
    try:
        frame_counts.append(len([f for f in os.listdir(vdir) if f.endswith('.png')]))
    except Exception:
        pass

fig, axes = plt.subplots(1, 3, figsize=(18, 4))

# 1) Split sample distribution
axes[0].bar(split_names, split_counts)
axes[0].set_title('Dataset Split (sample count)')
axes[0].set_ylabel('Count')

# 2) Label length distribution
axes[1].hist(label_lengths, bins=20)
axes[1].set_title('Label Length Distribution (train)')
axes[1].set_xlabel('Characters')
axes[1].set_ylabel('Frequency')

# 3) Frame count distribution
axes[2].hist(frame_counts, bins=20)
axes[2].set_title('Frame Count Distribution (train)')
axes[2].set_xlabel('Frames per sample')
axes[2].set_ylabel('Frequency')

plt.tight_layout()
plt.show()

print("Split counts:", dict(zip(split_names, split_counts)))
print(f"Avg label length: {np.mean(label_lengths):.2f}")
print(f"Avg frame count : {np.mean(frame_counts):.2f}")

# Additional visualizations: label length vs frame count + character distribution

vis_ds = dataset_vis if 'dataset_vis' in globals() else (ds if 'ds' in globals() else AirTypingDataset(opts, opts.data_path_train))

# Recompute safely to keep lengths aligned
labels_vis = vis_ds.labels
label_lengths_vis = [len(x) for x in labels_vis]
frame_counts_vis = [
    len([f for f in os.listdir(vdir) if f.endswith('.png')])
    for vdir in vis_ds.video_list
]

# Character-level class distribution (English)
char_counter = collections.Counter("".join(labels_vis).lower())
char_counts = [char_counter.get(ch, 0) for ch in ALPHABET]

# Correlation
corr = np.corrcoef(label_lengths_vis, frame_counts_vis)[0, 1] if len(label_lengths_vis) > 1 else float('nan')

fig, axes = plt.subplots(1, 2, figsize=(16, 5))

# 1) Scatter: label length vs frame count
axes[0].scatter(label_lengths_vis, frame_counts_vis, s=10, alpha=0.35)
axes[0].set_title(f'Label Length vs Frame Count (train)\nPearson r={corr:.3f}')
axes[0].set_xlabel('Label length (characters)')
axes[0].set_ylabel('Frame count')

# Optional trend line
if len(label_lengths_vis) > 1:
    z = np.polyfit(label_lengths_vis, frame_counts_vis, 1)
    p = np.poly1d(z)
    xs = np.linspace(min(label_lengths_vis), max(label_lengths_vis), 100)
    axes[0].plot(xs, p(xs), linewidth=2)

# 2) Class distribution: character frequency
axes[1].bar(list(ALPHABET), char_counts)
axes[1].set_title('Character Distribution (train labels)')
axes[1].set_xlabel('Character')
axes[1].set_ylabel('Count')
axes[1].tick_params(axis='x', rotation=90)

plt.tight_layout()
plt.show()

print(f"Samples: {len(labels_vis)}")
print(f"Pearson correlation (label length, frame count): {corr:.4f}")
print("Top 10 characters:", char_counter.most_common(10))

import os
import re

import matplotlib.pyplot as plt

log_path = os.path.join(trainer.save_dir, 'log-train.log')

epochs, val_losses, val_cers = [], [], []

if os.path.isfile(log_path):
    with open(log_path, 'r', encoding='utf-8', errors='ignore') as f:
        for line in f:
            m = re.search(r'val_loss=([0-9.]+)\s+val_cer=([0-9.]+)', line)
            if m:
                val_losses.append(float(m.group(1)))
                val_cers.append(float(m.group(2)))
                epochs.append(len(epochs) + 1)

    if epochs:
        fig, ax1 = plt.subplots(figsize=(10, 5))

        ax1.plot(epochs, val_losses, label='Validation Loss', color='tab:blue')
        ax1.set_xlabel('Epoch')
        ax1.set_ylabel('Loss', color='tab:blue')
        ax1.tick_params(axis='y', labelcolor='tab:blue')

        ax2 = ax1.twinx()
        ax2.plot(epochs, val_cers, label='Validation CER', color='tab:red')
        ax2.set_ylabel('CER', color='tab:red')
        ax2.tick_params(axis='y', labelcolor='tab:red')

        plt.title('Validation Loss and CER')
        fig.tight_layout()
        plt.show()
    else:
        print('No validation metrics found in the log file yet.')
else:
    print(f'Log file not found: {log_path}')

"""## Citation

```bibtex
@inproceedings{kim2021,
  title   = {Writing in The Air: Unconstrained Text Recognition from Finger Movement Using Spatio-Temporal Convolution},
  author  = {Ue-Hwan Kim and Yewon Hwang and Sun-Kyung Lee and Jong-Hwan Kim},
  journal = {arXiv preprint arXiv:2109.09021},
  year    = {2021}
}
```
"""